// FIREBASE
import {
  FIREBASE_API_KEY as _FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN as _FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID as _FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET as _FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGE_SENDER_ID as _FIREBASE_MESSAGE_SENDER_ID,
  FIREBASE_APP_ID as _FIREBASE_APP_ID,
} from '@env';

export const FIREBASE_API_KEY = _FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = _FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = _FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = _FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGE_SENDER_ID = _FIREBASE_MESSAGE_SENDER_ID;
export const FIREBASE_APP_ID = _FIREBASE_APP_ID;

// REDUX

export const USE_LOGGER = false;
export const CLEAR_REDUX = true;
